import { execSync } from "child_process";
import type { RunSummary, DiscoverResult } from "./types.js";

export function buildBranchName(date: string): string {
  return `documentator/nightly-${date}`;
}

export function detectGitProvider(remoteUrl: string): "github" | "bitbucket" | "unknown" {
  const override = process.env.DOCUMENTATOR_GIT_PROVIDER;
  if (override === "github" || override === "bitbucket") return override;

  if (remoteUrl.includes("github.com")) return "github";
  if (remoteUrl.includes("bitbucket.org")) return "bitbucket";
  return "unknown";
}

export function buildPrBody(summary: RunSummary): string {
  const lines: string[] = [
    "## Documentator Nightly Update",
    "",
    `**Date:** ${summary.date}`,
    `**Services tracked:** ${summary.services_tracked}`,
    `**Services changed:** ${summary.services_changed}`,
    `**Auto-escalated:** ${summary.services_auto_escalated}`,
    `**Triaged:** ${summary.services_triaged}`,
    `**Updated:** ${summary.services_updated}`,
    `**Tokens used:** ${summary.tokens_used}`,
    "",
  ];

  if (summary.services_failed.length > 0) {
    lines.push("### Failures");
    lines.push("");
    for (const f of summary.services_failed) {
      lines.push(`- **${f.name}**: ${f.error}`);
    }
    lines.push("");
  }

  if (summary.flows_relinked) {
    lines.push("Flows re-linked successfully.");
  } else if (summary.flows_skipped.length > 0) {
    lines.push("### Skipped Flows");
    lines.push("");
    for (const f of summary.flows_skipped) {
      lines.push(`- ${f}`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by Documentator nightly pipeline*");

  return lines.join("\n");
}

/**
 * Create per-service commits and a flow commit, then open/update a PR.
 */
export function createPr(
  kbDir: string,
  results: DiscoverResult[],
  flowsUpdated: boolean,
  summary: RunSummary
): string | null {
  const date = summary.date;
  const branch = buildBranchName(date);

  // Check for existing open documentator branch
  try {
    const existingBranches = execSync(
      `git -C "${kbDir}" branch -r --list "origin/documentator/nightly-*"`,
      { encoding: "utf-8", stdio: "pipe" }
    ).trim();

    if (existingBranches) {
      // Update existing branch
      execSync(`git -C "${kbDir}" checkout -B "${branch}"`, { stdio: "pipe" });
    } else {
      execSync(`git -C "${kbDir}" checkout -b "${branch}"`, { stdio: "pipe" });
    }
  } catch {
    execSync(`git -C "${kbDir}" checkout -b "${branch}"`, { stdio: "pipe" });
  }

  // One commit per updated service
  for (const result of results.filter((r) => r.success && r.manifestPath)) {
    execSync(`git -C "${kbDir}" add "${result.manifestPath}"`, { stdio: "pipe" });
    execSync(
      `git -C "${kbDir}" commit -m "docs(${result.service}): update service manifest" --allow-empty`,
      { stdio: "pipe" }
    );
  }

  // Flow + index commit
  if (flowsUpdated) {
    execSync(`git -C "${kbDir}" add flows/ index.yaml`, { stdio: "pipe" });
    execSync(
      `git -C "${kbDir}" commit -m "docs(flows): update flows and index" --allow-empty`,
      { stdio: "pipe" }
    );
  }

  // Push and create PR via adapter
  const remoteUrl = execSync(`git -C "${kbDir}" remote get-url origin`, {
    encoding: "utf-8",
    stdio: "pipe",
  }).trim();
  const provider = detectGitProvider(remoteUrl);

  execSync(`git -C "${kbDir}" push -u origin "${branch}" --force`, { stdio: "pipe" });

  const title = `Documentator nightly update ${date}`;
  const body = buildPrBody(summary);

  if (provider === "github") {
    try {
      const prUrl = execSync(
        `gh pr create --title "${title}" --body "${body.replace(/"/g, '\\"')}" --head "${branch}" 2>/dev/null || gh pr view "${branch}" --json url -q .url`,
        { encoding: "utf-8", cwd: kbDir, stdio: "pipe" }
      ).trim();
      return prUrl;
    } catch {
      return null;
    }
  }

  return null;
}

/**
 * Call the notification hook with the run summary.
 */
export function notify(hookPath: string | null, summary: RunSummary): void {
  if (!hookPath) return;

  try {
    execSync(`bash "${hookPath}"`, {
      input: JSON.stringify(summary, null, 2),
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30_000,
    });
  } catch {
    // Notification failure should not fail the pipeline
    console.error(`Warning: notification hook failed: ${hookPath}`);
  }
}
